version: '3.7'
services:
  members_events_db:
    container_name: members_events_db
    profiles:
      - dev
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - members_events_data:/var/lib/postgresql/data
    tty: true
    ports:
      - 5432:5432

  dev_server:
    container_name: dev_server
    profiles:
      - dev
      - prod
    build:
      context: .
      target: dev
    env_file:
      - .env
    depends_on:
      - members_events_db
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
    command: bash -c "npx prisma generate && npm run start:dev"

volumes:
  members_events_data: