name: Docker Build & Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: cfc-app
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --target dev .

      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
